"""Constants for Xuehua."""

OLLAMA_DEFAULT_URL = "http://localhost:11434"
DEFAULT_CHAT_MODEL = ""
DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"
DEFAULT_LANGUAGE = "ja"
DEFAULT_UI_LANGUAGE = "zh"
DEFAULT_CHUNK_SIZE = 800
DEFAULT_CHUNK_OVERLAP = 150
DEFAULT_TOP_K = 15
DEFAULT_RAG_DISTANCE_THRESHOLD = 1.5
DEFAULT_RAG_CONTEXT_LIMIT = 3000
MIN_CHUNK_LENGTH = 50
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5050

JLPT_LEVELS = ["N5", "N4", "N3", "N2", "N1"]
KANJI_ROMAJI_SYSTEMS = ["hepburn", "nippon", "passport"]

APP_NAME = "Xuehua"
APP_VERSION = "0.1.0"